version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik_bank_account
    command:
      - "--api.insecure=true" # Pour accéder au dashboard Traefik
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Important pour ne pas exposer tous les conteneurs par défaut
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443" # On prépare pour le HTTPS plus tard
      # Activation du dashboard (optionnel, mais pratique)
      - "--api.dashboard=true"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Traefik Dashboard (si --api.insecure=true est activé)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Permet à Traefik de lire les événements Docker
    networks:
      - web
    labels:
      - "traefik.enable=true" # Active Traefik pour lui-même (pour le dashboard)
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.bank.localhost`)" # Accès au dashboard
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_bank_account
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # Persistance des données Portainer
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.bank.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  db:
    image: postgres:15 # Ou mysql:8.0 si tu préfères
    container_name: db_bank_account
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-drupal}
      POSTGRES_USER: ${DB_USER:-drupal}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-drupal}
    volumes:
      - db_data:/var/lib/postgresql/data # Persistance des données PostgreSQL
    networks:
      - internal
    expose:
      - 5432

  drupal:
    image: drupal:10-php8.2-apache # Utilisation d'une image Drupal récente
    container_name: drupal_bank_account
    restart: always
    depends_on:
      - db
    volumes:
      - drupal_modules:/var/www/html/modules/custom # Pour les modules custom
      - drupal_profiles:/var/www/html/profiles/custom # Pour les profils custom
      - drupal_sites:/var/www/html/sites # Configuration des sites, settings.php, files
      - drupal_themes:/var/www/html/themes/custom # Pour les thèmes custom
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: ${DB_NAME:-drupal}
      DRUPAL_DB_USER: ${DB_USER:-drupal}
      DRUPAL_DB_PASSWORD: ${DB_PASSWORD:-drupal}
      DRUPAL_SITE_NAME: "Bank Account Analyzer"
      # Pour le développement, désactiver le cache de Twig et activer le mode debug
      # TWIG_CONFIG_debug: 'true'
      # TWIG_CONFIG_cache: 'false'
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`${APP_DOMAIN:-drupal.bank.localhost}`)"
      - "traefik.http.routers.drupal.entrypoints=web"
      - "traefik.http.services.drupal.loadbalancer.server.port=80"

networks:
  web:
    external: false
    name: traefik_public_network
  internal:
    external: false
    name: bank_account_internal_network

volumes:
  db_data:
  portainer_data:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
